import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Import Google Fonts via link tag */}
        
      </Head>
      <body className="antialiased myFont">{children}</body>
    </html>
  );
}
